#Task1-Perform Basic Mathematical Operations
number1 = input("Enter the first number: ")
number2 = input("Enter the Second number: ")
Addition = int(number1) + int(number2)
number3 = input("Addition :")
print(Addition)
Subtraction = int(number1) - int(number2)
number4 =input("Subtraction:  ")
print(Subtraction)
Multiplication = int(number1) * int(number2)
number5 = input("Multiplication :  ")
print(Multiplication)
Division = int(number1) / int(number2)
number6 =input("Division:  ")
print(Division)